name: Scheduled
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'
jobs:
  md-dead-link-check:
    name: Check all links weekly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check all links
        uses: AlexanderDokuchaev/md-dead-link-check@v1.3.0
        with:
          config: .config/md_dead_link_check.ini
